### ISSUE TITLE
Applying IBQ to Multi-Mcale VQVAE in VAR

### ISSUE THREAD

**Issue by RohollahHS** [TencentARC/SEED-Voken#42]
Hi, Great work.

Can IBQ be applied to the Multi-Scale VQVAE in VAR? and did you try it?

Thanks

**Comment by ShiFengyuan1999** [comment]
Hi @RohollahHS, thanks for your interest in our work. 

IBQ aims to render all codes differentiable and update the entire codebook in each backward process to ensure consistency with the distribution of the visual encoder by index backpropagation. It is compatible with other widely used quantization tricks like multi-scale and residual quantization. We did not try these for simplicity. It is easy to combine IBQ with these methods, by replacing the indices achieved by these methods with  https://github.com/TencentARC/SEED-Voken/blob/3c58097c358ce5bde74b9331cc32e98599a79a3f/src/IBQ/modules/vqvae/quantize.py#L448 in IBQ.

**Comment by RohollahHS** [comment]
Thanks for the information and your reply.
